src/core/core_api/urls.py
from django.urls import path
from .views import GetLatestTestSuite, GetLatestTest

urlpatterns = [
    path('get-latest-test-suite/',
         GetLatestTestSuite.as_view(),
         name='getLatestTestSuite'),
    path('get-latest-test/<name>/',
         GetLatestTest.as_view(),
         name='getLatestTest'),
]

src/core/urls.py
from django.urls import path
from . import views

app_name='core'

urlpatterns = [

    path('', views.index, name='home'),
    path('tests/', views.tests, name='tests'),
    path('tests/run', views.run, name='run'),

    ### URL FOR FUNCTIONS THAT LAUNCH AND MANAGE TEST SCRIPTS
    path('tests/run/all', views.runAllStart, name='runAllStart'),
    path('tests/run/<script>', views.runSingleTest, name='runSingleTest'),
    path('tests/run/all/cancel', views.cancelAllTests, name='cancelAllTests'),
    path('tests/mark-as-started/', views.markAsStarted, name='markAsStarted'),
    path('tests/mark-as-finished/', views.markAsFinished, name='markAsFinished'),
]

src/multitest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('api/', include('core.core_api.urls')),
    path('stats/', include('stats.urls'))
]

src/stats/urls.py
from django.urls import path
from . import views

app_name='stats'


urlpatterns = [

    path('latest/', views.latest, name='latest'),
    path('by-id/', views.byId ,name='by-id'),
    path('by-id/<testSuiteId>/', views.byIdResult, name='by-id-result'),
    path('compare/', views.compare, name='compare'),
    path('compare/<start_date>/<end_date>', views.compareResult, name='compare-result'),

    ### BOKEH GRAPHS GETTERS ####
    path('get-bokeh/<testSuiteId>', views.getBokeh, name='get-bokeh'),
    path('get-bokeh-compare/<start_date>/<end_date>', views.getBokehCompare, name='get-bokeh-compare')
]

src/core/models/mongo_setup.py
import mongoengine


def global_init(db_name: str):
    mongoengine.register_connection(
        alias='core',
        name=db_name,
        username='user',
        password='user',
        authentication_source='admin',
        host='db' # delete this line if you're not using docker
    )

src/core/models/test_dao.py
import logging

from .mongo_setup import global_init
from .test_suites import TestSuite
from .tests import Test
from .test_document import TestDocument

# from src.core.models.mongo_setup import global_init
# from src.core.models.test_document import TestDocument
# from src.core.models.test_suites import TestSuite
# from src.core.models.tests import Test

logger = logging.getLogger(__name__)


class TestDAO:
    """Executes queries on the DB and returns results"""

    def __init__(self):
        self.connect()

    def connect(self):
        try:
            global_init('tests')
        except Exception as e:
            logger.error("Could not establish a connection to DB: {}".format(e))

    def getAllTestSuites(self):
        try:
            testSuites = TestSuite.objects()
            logger.info("test suits: {}".format(testSuites))
            return testSuites
        except Exception as e:
            logger.error("Error in TestDAO.getAllTestSuites: {}".format(e))

    def getRangeTestSuite(self, start_date, end_date):
        try:
            query = TestSuite.objects(created__gte=start_date,
                                     created__lte=end_date)
            logger.info("Result query from getRangeTestSuite: {}".format(query))
            return query
        except Exception as e:
            logger.error("Exception at TestDAO.getRangeTestSuite: {}".format(e))

    def getTestSuiteById(self, id: str) -> TestSuite:
        try:
            return TestSuite.objects(testSuiteId=id)[0]
        except Exception as e:
            logger.error("Exception in TestDAO.getTestSuiteById: {}".format(e))

    def getLatestTestSuite(self):
        try:
            testSuite = TestSuite.objects.order_by('-created').first()
            if testSuite is None:
                return None
            return TestDAOHelper.TestSuiteToDict(testSuite)
        except Exception as e:
            logger.error("Error in getLatestTestSuite: {}".format(e))

    def getLatestTest(self, name) -> dict:
        try:
            testDocument = TestDocument.objects(test__name=name).order_by('-created').first()
            serializedDict = TestDAOHelper().serializeTest(testDocument.test)
            serializedDict.update({'created': testDocument.created})
            return serializedDict
        except Exception as e:
            logger.error("Exception in TestDAO.getLatestTest: {}".format(e))

    def addSingleTest(self, test):
        try:
            testDocument = TestDocument()
            testDocument.test = test
            testDocument.save()
            logger.info("Adding test to test document: {}".format(test))
        except Exception as e:
            logger.error("Exception in TestDAO.addSingleTest: {}".format(e))

    def addTestToTestSuite(self, test: Test, id: str) -> bool:
        try:
            querySet = TestSuite.objects(testSuiteId=id)
            if querySet:  # if there's a TestSuite with given id in query set
                testSuite = querySet[0]  # get this TestSuite
            else:  # create new TestSuite obj in db and set id
                testSuite = TestSuite()
                testSuite.testSuiteId = id
            testSuite.tests.append(test)
            testSuite.save()
            return True
        except Exception as e:
            logger.error("Could not add test ({}) to TestSuite: {}".format(test, e))
            return False

    def addDurationToTestSuite(self, id: str, time: float):
        try:
            testSuite = self.getTestSuiteById(id)
            logger.info("Adding duration ({}s) to TestSuite: {} ".format(time, TestSuite))
            testSuite.duration = time
            testSuite.save()
        except Exception as e:
            logger.error("Exception in TestDAO.persistTestSuiteDuration: {}".format(e))

    def markTestAsFinished(self, testSuiteId: str):
        try:
            testSuite = self.getTestSuiteById(testSuiteId)
            testSuite.is_finished = True
            testSuite.save()
        except Exception as e:
            logger.error("Could not mark test suit as finished: {}".format(e))


class TestDAOHelper:

    @classmethod
    def TestSuiteToDict(cls, testSuite: TestSuite) -> dict:
        if testSuite is None:
            return
        return {
            'created': str(testSuite.created),
            'testSuiteId': str(testSuite.testSuiteId),
            'duration': testSuite.duration,
            'is_finished': testSuite.is_finished,
            'tests': [TestDAOHelper.serializeTest(test) for test in testSuite.tests]
        }

    @classmethod
    def serializeTest(cls, test: Test) -> dict:
        return {
            'test_id': str(test.test_id),
            'name': str(test.name),
            'targetEnv': str(test.targetEnv),
            'duration': test.duration,
            'err': str(test.err),
            'out': str(test.out)
        }

src/core/models/test_document.py
import mongoengine
from .tests import Test
from datetime import datetime


class TestDocument(mongoengine.Document):
    """Mongo document to store Test instance, which is an Embedded document"""
    created = mongoengine.DateTimeField(default=datetime.utcnow)
    test = mongoengine.EmbeddedDocumentField(Test)

    meta = {
        'db_alias': 'core',
        'collection': 'singleTest',
        'indexes': ['created'],
        'ordering': ['created']
    }

src/core/models/test_suites.py
import mongoengine
from datetime import datetime
import logging

from .tests import Test

logger = logging.getLogger(__name__)

class TestSuite(mongoengine.Document):
    created = mongoengine.DateTimeField(default=datetime.utcnow)
    testSuiteId = mongoengine.StringField()
    tests = mongoengine.ListField(mongoengine.EmbeddedDocumentField(Test))
    duration = mongoengine.FloatField()
    is_finished = mongoengine.BooleanField()

    meta = {
        'db_alias': 'core',
        'collection': 'TestSuite',
        'indexes': [
            'created',
            'testSuiteId',
        ],
        'ordering': ['testSuiteId']
    }

src/core/models/tests.py
import mongoengine

class Test(mongoengine.EmbeddedDocument):
    test_id = mongoengine.StringField()
    name = mongoengine.StringField()
    targetEnv = mongoengine.StringField()
    duration = mongoengine.FloatField()
    err = mongoengine.StringField()
    out = mongoengine.StringField()

    meta = {
        'db_alias': 'core',
        'collection': 'test',
        'indexes': [
            'id',
            'name',
            'duration',
        ],
        'ordering': ['id'],
    }

src/core/core_api/views.py
from rest_framework import views
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from .serializers import TestSuiteSerializer, SingleTestSerializer
from ..models.test_dao import TestDAO


class GetLatestTestSuite(views.APIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def get(self, request):
        data = TestDAO().getLatestTestSuite()
        results = TestSuiteSerializer(data)
        return Response(results.data)


class GetLatestTest(views.APIView):
    permission_classes = (IsAuthenticatedOrReadOnly,)

    def get(self, request, name):
        data = TestDAO().getLatestTest(name)
        results = SingleTestSerializer(data)
        return Response(results.data)

src/core/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

import logging

from .services.tasks_services import TaskManager
from .services.init_tests import TestServiceHelper
from .tasks import startAllTestsTask, startSingleTest

logger = logging.getLogger(__name__)
taskManager = TaskManager()
testServiceHelper = TestServiceHelper()


@login_required
def index(request):
    return render(request, template_name='core/index.html')


@login_required
def tests(request):
    scripts = testServiceHelper.getScripts()
    scripts_ids = [i for i in range(len(scripts))]
    scripts = [script.split(".")[0] for script in scripts]  # get rid of '.py'

    return render(
        request=request,
        template_name='core/tests.html',
        context= {'scripts': zip(scripts, scripts_ids)}
    )


@login_required
def run(request: WSGIRequest):
    context = {'should_launch': True}
    is_running = request.session.get('is_running','')
    logger.info("FROM RUN: IS RUNNING {}".format(is_running))
    if is_running:
        context['should_launch'] = False
    return render(request=request,
                  template_name='core/run.html',
                  context=context)


### TEST SCRIPT LAUNCHERS ###

@login_required
def runAllStart(request: WSGIRequest):
    signature = taskManager.createSignature(startAllTestsTask)
    result = taskManager.startTask(signature)  # GroupResult
    taskManager.collectResult(result)
    return HttpResponse("Launched all tests")

@login_required
def runSingleTest(request: WSGIRequest, script):
    logger.info("Launching single test: {}".format(script))
    script += '.py'
    cmd = testServiceHelper.getCommand(script)
    taskSignature = taskManager.createSignature(startSingleTest, command=cmd)
    taskManager.startTask(taskSignature)  # fire acutal task

    return HttpResponse("Launching %s" % script)

@login_required
def cancelAllTests(request):
    try:
        taskManager.revoke()
    except Exception as e:
        print("Exception in cancelAllTests: ", e)
    return HttpResponse("REVOKED")

@login_required
def markAsStarted(request):
    """
    It's being called inside run.html after launching all tests, to prevent
    launching scripts again (for example after refreshing.
    After launching tests, 'is_running' is set to True in session.
    """
    request.session['is_running'] = True
    return HttpResponse("IS_RUNNING = TRUE")

@login_required
def markAsFinished(request):
    request.session['is_running'] = False
    return HttpResponse("IS_RUNNING = FALSE")

src/templates/core/index.html
{% extends 'core/layout.html' %}
{% block content %}
<h1>HI {{user}}</h1>
{% endblock %}
{% block content2 %}
<p>LAUNCH ALL TESTS IN THE BACKGROUND IN ORDER TO TEST YOUR ENTIRE WEBSITE
FUNCTIONALITY.</p>
<p>OR SELECT A SINGLE TEST TO RUN.</p>
<p>YOU CAN SEE TESTS HISTORY AND STATISTICS.</p>
{% endblock %}

src/templates/core/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Test Management</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'core:home' %}">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              RUN TESTS
            </a>
            <div class="dropdown-menu" style="align:center" aria-labelledby="">
              <a class="dropdown-item stats" href="{% url 'core:run' %}">&nbsp;&nbsp;ALL</a><br>
              <a class="dropdown-item stats" href="{% url 'core:tests' %}">&nbsp;&nbsp;BY NAME</a><br>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              STATISTICS
            </a>
            <div class="dropdown-menu" style="align:center" aria-labelledby="">
              <a class="dropdown-item stats" href="{% url 'stats:latest' %}">&nbsp;&nbsp;LATEST STATS</a><br>
              <a class="dropdown-item stats" href="{% url 'stats:by-id' %}">&nbsp;&nbsp;GET BY DATE</a><br>
                <a class="dropdown-item stats" href="{% url 'stats:compare' %}">&nbsp;&nbsp;COMPARE TS</a><br>
            </div>

          </li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">LOGOUT</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid bg-1 text-center">
    {% block content %}
    {% endblock %}
</div>

<div class="container-fluid bg-3 text-center">
    {% block content2 %}
    {% endblock %}
</div>

<footer class="container-fluid bg-4 text-center">
  <p>FOOTER</p>
</footer>

</body>
</html>

src/templates/core/run.html
{% extends 'core/layout.html' %}
{% load static %}

{% block head %}
    <script src={% static 'js/createDivForTestResult.js' %}></script>
    <script src={% static 'js/toggleOut.js' %}></script>
    <script src={% static 'js/isExists.js' %}></script>
    <script src={% static 'js/launchMultitest.js' %}></script>
    <script src={% static 'js/markAsFinished.js' %}></script>
{% endblock %}

{% block content %}
<body>
   <div id="zero">
        <div id="one">
            <h2 class="status">Running...</h2>
        </div>
        <div id="two">
            <div class="loader"></div>
        </div>
        <button id="cancel" class="btn btn-dark">CANCEL</button>
    </div>
</body>

{% endblock %}

{% block content2 %}

    <div>
      <div class="result">
        <h3>RESULTS</h3>
      </div>
    </div>

    <script>
        $(window).ready( () => {
            {% if should_launch %} // LAUNCH TESTS WHEN PAGE LOADS
                console.log("Launched tests")
                launchTests();
                markAsStarted();
                // ADD EVENT LISTENER TO CANCEL BUTTON TO TERMINATE TESTS
                let cancel = document.querySelectorAll('button[id=cancel]')[0];
                cancel.addEventListener("click", cancelTests);
            {% else %}
                console.log("Not launching")
                cleanUp();
                markAsFinished();
                return;
            {% endif %}
        });
    </script>

{% endblock %}

src/templates/core/tests.html
{% extends 'core/layout.html' %}
{% load static %}
{% block content %}
    <div class="col-sm-6">
          {% for script, script_id in scripts %}
            <div class="btn-group btn-group-toggle" data-toggle="buttons">

                <input
                    type="button"
                    name="button"
                    class="btn btn-outline-dark test-button"
                    id="submit"
                    value="{{script}}"
                />

            </div><br>
          {% endfor %}
      </div>
    <div class="col-sm-6" name="queue">
        <h1>QUEUE</h1>
        <div id="queue-elements">
        </div>
    </div>

    <script src="{% static 'js/createListenersAndLaunchTest.js' %}"></script>
    <script src="{% static 'js/singleTestQueueActions.js' %}"></script>
{% endblock %}

{% block content2 %}
    
    <div id="spin">
        <h3>Results</h3>
    </div>
    <div name="results"></div>

{% endblock %}